[theme]
primaryColor = '#b488fb'                #
backgroundColor = '#f4f1fc'             # background
secondaryBackgroundColor = '#d6c9f7'    # sidebar and input bars
textColor = '#2e1e60'
font = 'sans serif'